config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

# Temporary
from .views import home

urlpatterns = [
    path(settings.ADMIN_PATH + '/', admin.site.urls),
    # path('auth/', include('custom_auth.urls')),  # Optional
    path('', home, name='home'),  # Temporary
    path('', include('custom_pwa.urls')),
]

custom_auth/urls.py
from django.urls import path, re_path
from .views import (
    login_view,
    logout_view,
    signup_view,
    resend_confirmation,
    activate,
    account_view,
    account_edit,
    account_delete,
    premium_view,

    create_checkout_session,
    customer_portal,
    webhook_received,
    payment_success,
    payment_cancel,
    cancel_subscription,
)

app_name = 'custom_auth'

urlpatterns = [
    path('create-checkout-session/', create_checkout_session, name='create_checkout_session'),
    path('create-portal-session/', customer_portal, name='customer_portal'),
    path('webhook/', webhook_received, name='webhook_received'),
    path('payment-success/', payment_success, name='payment_success'),
    path('payment-cancel/', payment_cancel, name='payment_cancel'),
    path('cancel-subscription/', cancel_subscription, name='cancel_subscription'),

    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('account/', account_view, name='account_view'),
    path('account/edit/', account_edit, name='account_edit'),
    path('account/delete/', account_delete, name='account_delete'),
    path('premium/', premium_view, name='premium_view'),
    re_path(r'^re-send-confirmation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        resend_confirmation, name='resend_confirmation'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        activate, name='activate'),
]

custom_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True, blank=False, null=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

custom_auth/forms.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, Form
from django import forms
# from .models import CustomUser

from django.contrib.auth import get_user_model
UserModel = get_user_model()


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = UserModel
        fields = UserCreationForm.Meta.fields + ('email',)

        # TODO: Change placeholders

        labels = {
            "password2": _("Confirm Password")
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["placeholder"] = "username"
        self.fields["username"].widget.attrs["class"] = "input"
        self.fields["username"].widget.attrs["autofocus"] = True

        self.fields["email"].widget.attrs["placeholder"] = "email"
        self.fields["email"].widget.attrs["class"] = "input"
        self.fields["email"].widget.attrs["autofocus"] = False
        
        self.fields["password1"].widget.attrs["placeholder"] = "password"
        self.fields["password1"].widget.attrs["class"] = "input"
        
        self.fields["password2"].widget.attrs["placeholder"] = "password again"
        self.fields["password2"].widget.attrs["class"] = "input"

        
class CustomUserLoginForm(Form):

    username = forms.CharField(
        label=_('Email/Username'),
        max_length=150, 
        required=True,
        widget=forms.TextInput(
            attrs={'placeholder': 'email or username', 'class': 'input'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'password', 'class': 'input'}), 
        required=True
    )


class CustomUserEditForm(ModelForm):

    username = forms.CharField(
        label       = _('Username'),
        max_length  = 150, 
        required    = False,
        widget      = forms.TextInput(
            attrs={'placeholder': 'username', 'class': 'input'}
        )
    )

    email = forms.EmailField(
        label       = _('Email'),
        max_length  = 150,
        required    = False,
        widget      = forms.TextInput(
            attrs={'placeholder': 'email', 'class': 'input'}
        )
    )

    class Meta:
        model = UserModel
        fields = ('username', 'email')


class CustomUserDeleteForm(ModelForm):

    password = forms.CharField(
        label = _('Password'),
        max_length = 128,  # TODO: What is the max_length in models.py
        required = True,
        widget = forms.PasswordInput(
            attrs={'placeholder': 'password', 'class': 'input'}
        )
    )

    class Meta:
        model = UserModel
        fields = ('password',)

custom_auth/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.hashers import check_password

YOUR_DOMAIN = settings.ENV_DOMAIN

# Mine
from .forms import (
    CustomUserCreationForm, 
    CustomUserLoginForm, 
    CustomUserEditForm,
    CustomUserDeleteForm,
)
from .send_email import send_email

# Sendgrid
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token

UserModel = get_user_model()


@user_passes_test(lambda user: user.is_anonymous, login_url='/', redirect_field_name=None)
def signup_view(request):

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            token = account_activation_token.make_token(user)
            email = form.cleaned_data.get('email')

            current_site = get_current_site(request)
            
            html_content = render_to_string('custom_auth/email/activate_account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': token,
            })

            subject = 'Confirmation e-mail for My New Website'
            
            send_email(request, email, subject, html_content)
                
            message_content = render_to_string('custom_auth/email/resend_confirmation.html', {
                'email': email,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': token,
            })

            messages.info(request, message_content)
            return redirect('custom_auth:login')
        else:
            print('Form is NOT valid...')
    else:
        form = CustomUserCreationForm()

    context = {'form': form, 'active': 'signup'}
    return render(request, 'custom_auth/signup.html', context)


def resend_confirmation(request, uidb64, token):

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = UserModel.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        email = user.email
        
        current_site = get_current_site(request)
        html_content = render_to_string('custom_auth/email/activate_account.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': token,
        })
            
        subject = 'Re-send confirmation email'  # Probably not necessary
        send_email(request, email, subject, html_content)

        html_content = render_to_string('custom_auth/email/resend_confirmation.html', {
            'email': email,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': token,
        })
        messages.info(request, html_content)
    else:
        messages.error(request, 'Activation link is invalid or User does not exist.')

    return redirect('custom_auth:login')


def activate(request, uidb64, token):

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = UserModel.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend=settings.AUTHENTICATION_BACKENDS[0])

        messages.success(request, 'Email has been verified!')
    else:
        messages.error(request, 'Activation link is invalid')

    return redirect('generator:home')


@user_passes_test(lambda user: user.is_anonymous, login_url='/', redirect_field_name=None)
def login_view(request):

    if request.method == 'POST':
        form = CustomUserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = None
            try:
                email = validate_email(username)
            except ValidationError as e:
                print("Bad Email:", e)

            password = form.cleaned_data.get('password')

            user = authenticate(email=email, username=username, password=password)
            if user is not None:
                login(request, user, backend=settings.AUTHENTICATION_BACKENDS[0])
                username = request.user
                messages.success(request, f'Logged in as {username}')
                return redirect('generator:home')
            else:
                # Check if user is active. If not then redirect to login page with message.
                user = None
                try:
                    user = UserModel.objects.get(username=username)
                except UserModel.DoesNotExist as e:
                    print('user does not exist...')
                
                if user.is_active:
                    # print('User is active. Something went wrong.')
                    pass
                else:  # User is not active

                    email = user.email
                    token = account_activation_token.make_token(user)
                    
                    current_site = get_current_site(request)
                    html_content = render_to_string('custom_auth/email/login_fail_resend_confirmation.html', {
                        'email': email,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': token,
                    })
                    messages.error(request, html_content)
                    return redirect('custom_auth:login')

                # print('User:', user, user.is_active)
                # print('User is none...')
        else:
            # print('Form is not valid...')
            pass

    else:
        form = CustomUserLoginForm()


    context = {'form': form, 'active': 'login'}
    return render(request, 'custom_auth/login.html', context)


@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'Successfully logged out!')
    return redirect('generator:home')


@login_required
def account_view(request):
    user = None
    user = request.user

    form_delete = CustomUserDeleteForm()
    context = {'active': 'account','user': user, 'form_delete': form_delete}
    return render(request, 'custom_auth/account_view.html', context)


@login_required
def account_edit(request):
    user = request.user
    
    if request.method == 'POST':
        form = CustomUserEditForm(request.POST or None, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your account details have beend updated.')
            return redirect('custom_auth:account_view')
        else:
            messages.error('Details invalid!')
            return redirect('custom_auth:account_edit')
    else:
        form = CustomUserEditForm(instance=user)

    context = {'form': form}
    return render(request, 'custom_auth/account_edit.html', context)


@login_required
def account_delete(request):
    user = request.user
    username = user.username
    if request.method == 'POST':
        form = CustomUserDeleteForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            encoded_password = user.password
            passed = check_password(password, encoded_password)
            if passed:
                user.delete()
                messages.success(request, f'Your account "{username}" has been deleted')
                return redirect('generator:home')

    messages.error(request, f'Could not delete account "{username}"')
    return redirect(request, 'custom_auth:account_view')

custom_auth/templates/custom_auth/account_edit.html
{% extends 'generator/base.html' %}
{% load static %}

{% block content %}
<form action="{% url 'custom_auth:account_edit' %}" method="POST" class="auth__form">
    {% csrf_token %}
    {{form.username}}
    {{form.email}}
    <input type="submit" value='Save' class="btn btn--outline input">
</form>
{% endblock content %}

custom_auth/templates/custom_auth/account_view.html
{% extends 'generator/base.html' %}
{% load static %}

{% block content %}

<div class="cover hidden" data-account-view-cover=""></div>

<div class="model_view__container">
    
    <div class="model_view__field_container box-shadow-none">
        <a href="{% url 'custom_auth:account_edit' %}" class="btn btn--outline">
            Edit Account Details
        </a>
    </div>
    
    <div class="model_view__field_container">
        <div class="model_view__field_container__key">Premium User</div>
        <a 
            href="{% url 'custom_auth:premium_view' %}" 
            class="model_view__field_container__val model_view__field_container__val__a"
            style="display: flex; justify-content: center;"    
        >
            {% if user.is_premium == True %}
                <i class="fas fa-crown fa-crown-custom"></i>
            {% else %}
                Upgrade
            {% endif %}
        </a>
    </div>
    
    {% if user.is_premium == True %}
    <div class="model_view__field_container">
        <div class="model_view__field_container__key">Payment Info</div>
        {% if user.session_id != null %}
        <!-- TODO: Make this button fill the container -->
            <form 
                action="{% url 'custom_auth:customer_portal' %}" 
                method="POST" class="model_view__field_container__val model_view__field_container__val__form p-0"
            >
                {% csrf_token %}
                <input type="hidden" id="session-id" name="session_id" value="{{user.session_id}}" />
                <input id="checkout-and-portal-button" type="submit" value="Manage your billing information &gt;">
            </form>
        {% else %}
            <div class="model_view__field_container__val">
                Unable to retrieve payment information
            </div>
        {% endif %}
    </div>
    {% endif %}

    <div class="model_view__field_container">
        <div class="model_view__field_container__key">Username</div>
        <div class="model_view__field_container__val">{{user.username}}</div>
    </div>

    <div class="model_view__field_container">
        <div class="model_view__field_container__key">Email</div>
        <div class="model_view__field_container__val">{{user.email}}</div>
    </div>

    <div class="model_view__field_container">
        <div class="model_view__field_container__key">Date Created</div>
        <div class="model_view__field_container__val">{{user.date_joined}}</div>
    </div>

    <div class="model_view__field_container box-shadow-none" data-delete-account-popup-trigger="">
        <div class="btn btn--outline btn--outline--danger">Delete Account</div>
    </div>
    <form 
        action="{% url 'custom_auth:account_delete' %}" method='POST'
        id="form_delete_popup" class="hidden"
    >
        {% csrf_token %}
        {{form_delete.password}}
        <input type="submit" value="Delete Account" class="btn btn--outlin btn--danger">
    </form>

</div>


<script src="{% static 'js/pages/account_view.js' %}"></script>
{% endblock content %}

custom_auth/templates/custom_auth/login.html
{% extends 'generator/base.html' %}
{% load static %}

{% block content %}
<form action="{% url 'custom_auth:login' %}" method="POST" class="auth__form">
    {% csrf_token %}
    {{form.username}}
    {{form.password}}
    <input type="submit" value='Login' class="btn btn--outline input">
    <hr class="hr">
    <a href="{% url 'custom_auth:signup' %}" class="btn btn--outline">Register</a>
</form>
{% endblock content %}

custom_auth/templates/custom_auth/premium.html
{% extends 'generator/base.html' %}
{% load static %}

{% block content %}
    
    <!-- Display a payment form -->
    <form 
        action="{% url 'custom_auth:create_checkout_session' %}" 
        method="POST" id="payment-form"
        class="form__premium"
    >
        {% csrf_token %}

        {% for price in prices %}
            <div style="display: flex; align-items: center" class="form__premium__option">
                <input 
                    type="radio" 
                    name="premium_plan" 
                    id="{{price.id}}" 
                    value="{{price.id}}"
                    {% if price.interval == 'month' %}checked{% endif %}
                >

                <label for="{{price.id}}">
                    <div>£{{price.amount}} / {{price.interval}}</div> 
                    {% if price.interval == 'year' %}<span>(44% cheaper)</span>{% endif %}
                </label>
            </div>
        {% endfor %}

        
        <button
            id="submit" type="submit" 
            {% if user.is_premium == True %}disabled{% endif %}
            class="btn btn--outline"
        >
            Subscribe
        </button>
    </form>

    {% if user.is_premium == True and will_renew == False %}
        <div class="btn btn--danger btn__cancel-subscription" data-delete-account-popup-trigger="">
            Cancel Subscription
        </div>
        
        
        <div class="cover hidden" data-account-view-cover=""></div>
        <form 
            action="{% url 'custom_auth:cancel_subscription' %}" method='POST'
            id="form_delete_popup" class="hidden"
        >
            {% csrf_token %}
            <div style="margin-bottom: 2rem; text-align: center; font-size: 1.2rem;">
                Are you sure you want to end your subscription?
            </div>
            <input type="submit" value="Yes" class="btn btn--outlin btn--danger">
            <!-- TODO: Add option for "no" and add corresponding javascript code -->
        </form>
    {% endif %}

<script src="{% static 'js/pages/premium.js' %}"></script>
{% endblock content %}

custom_auth/templates/custom_auth/signup.html
{% extends 'generator/base.html' %}
{% load static %}

{% block content %}
<form action="{% url 'custom_auth:signup' %}" method="POST" class="auth__form">
    {% csrf_token %}
    <!-- TODO: Change placeholders in form and then remove labels and p tags -->
    {{form.username}}
    {{form.email}}
    {{form.password1}}
    {{form.password2}}
    <input type="submit" value="Signup" class="btn btn--outline input">
    <hr class="hr">
    <a href="{% url 'custom_auth:login' %}" class="btn btn--outline">Login</a>
</form>
{% endblock content %}